### ISSUE TITLE
Split README into Wiki

### ISSUE THREAD

**Issue by Aptimex** [sandialabs/wiretap#56]
The Readme is really long, would probably be more useful to have the different headings split into topics in a Wiki format.

**Comment by luker983** [comment]
The docs could certainly be better organized. I tend to prefer a table of contents and Cmd+F rather than having to rely on a wiki search bar and jumping between pages though. 

Moving the demo section to a Wiki page and linking to it from pretty high up in the existing readme would be a good first step I think.

**Comment by Aptimex** [comment]
@luker983 Can you review the new How it Works section in [this branch](https://github.com/sandialabs/wiretap/tree/readme-updates) and make sure I got it all right? In particular some clarification about how the API address relates to the Relay or E2EE interfaces would be helpful. Including how they get assigned, since I don't see them in the config files. 

Any other feedback on the Readme there is welcome too, but it's still a WIP

**Comment by luker983** [comment]
Sure! Looks good. Some feedback:

I think this section could probably be moved to the wiki as well since it's grown quite a bit. Maybe just leave the diagram and a link to the wiki page?

> This section is intended to provide an intuitive, working understanding of how Wiretap works, and may not be entirely technically accurate about implementation details.

I think we can do both, demonstrate the concepts without compromising accuracy

> These UDP connections occur over real-world TCP/IP network infrastructure. 

All of the network traffic occurs over "real-world" network infrastructure, we just add one additional layer over a traditional VPN. I think "overlay network" might be the most common term for this.

> Relay interfaces receive internal Wireguard IPs: 172.16.X.X for IPv4, and fd:16::X for IPv6.

This is all configurable, consider adding "By default, " before this line.

> Each Server is dynamically assigned an additional unique IP (usually an IPv6 address, such as ::2) inside the E2EE network to enable the secure usage of this API.

The API addresses are assigned just like the relay/e2ee peer IPs, it's an incrementing value kept track of by the first Server: https://github.com/sandialabs/wiretap/blob/readme-updates/src/transport/api/api.go#L262

They appear in the e2ee config under AllowedIPs (so the client has a route to the API). 

The API handler binds to the API address on the e2ee interface (internal to the program, the userspace networking stack, only reachable by clients).

**Comment by Aptimex** [comment]
Yeah the Details section is probably better off in a Wiki page, I'll move that. 

> I think we can do both, demonstrate the concepts without compromising accuracy
Fair, that was mostly in reference to my explanation of Servers acting like typical TCP/IP Routers, and I wasn't sure if that was actually how they worked under the hood. 

> All of the network traffic occurs over "real-world" network infrastructure
I'm trying to differentiate between traffic that is visible to "real world" devices (packets that have IP headers for routing to host NICs) vs. packets that only get routed inside the userspace Wiretap network and are effectively invisible to the hosts during transport. Since I'm already describing the "Relay" and "E2EE" virtual/overlay networks, "real-world" network seems like the most appropriate term to differentiate where those outer-most connections happen, but I'm open to better terminology ideas. 

Thanks for the API clarification, I've expanded on that section in the new Wiki page.
